#!/usr/bin/env bash
#
# Sets up the development environment for Bedrock

# Be damn sure
echo "***************************************************************"
echo "You are about to delete all git repositories in this directory."
echo "***************************************************************"
echo
read -p "Are you sure? (enter: 'do it *fist crush*' to proceed) " -r
echo    # (optional) move to a new line
if [ "$REPLY" != "do it *fist crush*" ]; then
  echo "DELETING EVERYTHING! Just kidding. Stay in school, kids."
  exit 0
fi

# Collect a list of all of the repositories
NPM_REPOS=`cat package.json | sed -n "/cloneRepos/,/\},/p" | sed '$d' | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`
BOWER_REPOS=`cat bower.json | sed -n "/cloneRepos/,/\},/p" | sed '$d' | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`

# Clone all of the repositories
echo -n "Deleting all repositories..."
for line in $NPM_REPOS $BOWER_REPOS;
do
  REPO_NAME=`echo $line | cut -f1 -d:`
  REPO_URL=`echo $line | cut -f2- -d: | cut -f1 -d#`
  
  echo -n "."
  rm -rf $REPO_NAME
done
echo "done."

# Remove node_modules
echo "Removing node_modules/"
rm -rf node_modules

# Remove bower_components
echo "Removing bower_components/"
rm -rf bower_components

echo "Destruction complete. Try ./setup if this made you a sad panda."
