#!/usr/bin/env bash
#
# Checks for changes in all repositories

# Collect a list of all of the repositories
NPM_REPOS=`cat package.json | sed -n "/cloneRepos/,/\},/p" | sed '$d' | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`
BOWER_REPOS=`cat bower.json | sed -n "/cloneRepos/,/\},/p" | sed '$d' | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`

# Check for changes in each repository
for line in $NPM_REPOS $BOWER_REPOS;
do
  REPO_NAME=`echo $line | cut -f1 -d:`
  echo -e "\nChecking $REPO_NAME..."
  cd $REPO_NAME
  git status --porcelain
  cd ..
done
echo "done."
