#!/usr/bin/env bash
#
# Sets up the development environment for Bedrock

# Collect a list of all of the repositories
NPM_REPOS=`cat package.json | sed -n "/cloneRepos/,/\},/p" | head -n-1 | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`
BOWER_REPOS=`cat bower.json | sed -n "/cloneRepos/,/\},/p" | head -n-1 | tail -n+2 | tr -d '"' | tr -d ',' | tr -d ' '`

# Update the current repository
echo -e "\nUpdating bedrock-dev..."
git pull -q --rebase
npm install
./node_modules/.bin/bower install

# Update all of the repositories
for line in $NPM_REPOS $BOWER_REPOS;
do
  REPO_NAME=`echo $line | cut -f1 -d:`
  echo -e "\nUpdating $REPO_NAME..."
  cd $REPO_NAME
  git pull -q --rebase
  npm install
  cd ..
done
echo "done."

echo "Update complete. Try this: nodejs ./index.js"
